version: '1.0'
name: pipeline-20221101
displayName: 部署
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - dev
stages:
  - name: stage-00010480
    displayName: 编译
    strategy: naturally
    trigger: auto
    executor:
      - mujinzjh
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: 构建
        nodeVersion: 16.14.2
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - ''
          - '# 执行编译命令'
          - npm install && npm run build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches: []
        notify: []
        strategy:
          retry: '0'
      - step: sc@opensca
        name: open_sca
        displayName: OpenSCA 开源组件检测
        detectPath: ./
        notify: []
        strategy:
          retry: '0'
        dependsOn: build_nodejs
  - name: stage-1ef7821b
    displayName: 部署
    strategy: naturally
    trigger: auto
    executor:
      - mujinzjh
    steps:
      - step: deploy@agent
        name: deploy_agent
        displayName: 主机部署
        hostGroupID:
          ID: ubuntu
          hostID:
            - 61527b9c-d860-4a62-8584-f3a0ba4da330
        deployArtifact:
          - source: artifact
            name: output
            target: ~/gitee_go/deploy
            artifactRepository: default
            artifactName: output
            artifactVersion: latest
        script:
          - echo 'Hello Gitee Go!'
          - sudo -i
          - mkdir -p /home/zjh/app/web
          - rm -rf /home/zjh/app/web/*
          - tar -zxf /home/lighthouse/gitee_go/deploy/output.tar.gz -C /home/zjh/app/web
          - cd /home/zjh/app/web
          - ls
          - ''
        notify: []
        strategy:
          retry: '0'
strategy:
  blocking: true
